### ISSUE TITLE
Moto C 4G (namath) kernel source

### ISSUE THREAD

**Issue by Mysteryagr** [MotorolaMobilityLLC/motorola-kernel#10]
Hi, I am waiting for Moto C 4G - XT1754 kernel source release
when it will be released?
Thanks in advance

**Comment by Mysteryagr** [comment]
@motorolamobility 
@charleseb
Who should I contact to release the source for my device?

**Comment by WTspm** [comment]
Hello, the Moto C 4G - XT1754 kernel source is released.
