### ISSUE TITLE
[Request] Harpia's 7.1.1 kernel source

### ISSUE THREAD

**Issue by ghost** [MotorolaMobilityLLC/motorola-kernel#12]
Hi MotorolaMobilityLLC,

I'd like to formally request you guys the source of Harpia's 7.1.1 kernel. We at XDA-Developers would love to work on this particular handset yet we are unable to if we cannot compile from the source and work from there.

The _about phone_ screen displays these items:

```
System Version: 26.21.39.harpia.retail.en.US
Model Number: Moto G Play
Android Version: 7.1.1
Baseband Version: M8916_20250112.18.05.45R
Build Id: NPI26.48-36
SW Display Build ID: NPI26.48-36
Build Date: Tue Nov 14 06:16:29 CST 2017
```

Any input from your end will serve of great help for future development work towards enhancing the experience of the community at XDA. :-D

Best,
-R.

**Comment by charleseb** [comment]
Hi @rottenwheel,

This version is in our pipeline and we'll release it soon. This version will be released by Friday.

Thanks,
Charles

**Comment by jame25** [comment]
Thanks Charles, your work is greatly appreciated.

**Comment by charleseb** [comment]
Hi @rottenwheel, @jame25,

Version released.
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-NPI26.48-36

Thanks,
Charles
