### ISSUE TITLE
@Oves786 ,

### ISSUE THREAD

**Issue by xda1982** [MotorolaMobilityLLC/motorola-kernel#14]
@Oves786 ,
Version released:
https://github.com/MotorolaMobilityLLC/kernel-slsi/releases/tag/MMI-QSB30.62-17
Thanks.

_Originally posted by @chenyt9 in https://github.com/MotorolaMobilityLLC/kernel-slsi/issues/4#issuecomment-607070534_

**Comment by vinimed** [comment]
Hello @xda1982, could you detail better what you looking for?
Thank you.

**Comment by vinimed** [comment]
Due to lack of response, I am closing the issue. If you still have questions, please reopen the issue and we can work on it.
