### ISSUE TITLE
Kernel Sources for moto e3 power 

### ISSUE THREAD

**Issue by diparthshah** [MotorolaMobilityLLC/motorola-kernel#4]

**Comment by charleseb** [comment]
Hi Diparth,

Could you please inform the build number you need?
You can find this information in _Settings -> About phone_.

---

Thanks,
Charles

**Comment by diparthshah** [comment]
@rohantaneja

**Comment by charleseb** [comment]
Hi @diparthshah,

A new Moto E tag has been released, please check this tag MMI-XT1706-S131-160905

https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-XT1706-S131-160905

Thanks,
Charles
