### ISSUE TITLE
Kernel Sources for Moto E3 Power

### ISSUE THREAD

**Issue by HostZero** [MotorolaMobilityLLC/motorola-kernel#5]
Device: taido_row
Model: XT1706
Build ID: XT1706_S131_160905_ROW
Chipset: MT6735M

Hope you will release kernel sources soon. @tags07

**Comment by charleseb** [comment]
Hi Haneesh,

We are working on the process to release this version.
It will be pushed to GitHub in a few days.

---

Thanks,
Charles

**Comment by HostZero** [comment]
@charleseb That's glad to hear! I have few questions.
1. Will there be a new repository as it's Mediatek?
2. Can you mention which defconfig must be used?

Thankyou

**Comment by shalinnn** [comment]
how much more time to release kernal source for moto e3 power

**Comment by NazarMohamed** [comment]
Please release the kernel source guys.
Thanks

**Comment by Aman301582** [comment]
Please release the source. Thanks.

**Comment by charleseb** [comment]
Hi @diparthshah,

A new Moto E tag has been released, please check this tag MMI-XT1706-S131-160905

https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-XT1706-S131-160905

Thanks,
Charles

**Comment by TdevM** [comment]
Yeah. Thanks!
