### ISSUE TITLE
Update potter source for camera

### ISSUE THREAD

**Issue by GtrCraft** [MotorolaMobilityLLC/motorola-kernel#9]
Can you please update potter's kernel source to the NPN25.137.67 release?
Camera is broken now

**Comment by charleseb** [comment]
Hi @GtrCraft,

I'm working to release this version, it will be available soon.

**Comment by charleseb** [comment]
Version is already released.
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-NPN25.137-67
